# Generated by Django 5.2 on 2025-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='検索キーワード')),
                ('source', models.CharField(max_length=50, verbose_name='ソースサイト')),
                ('results_json', models.JSONField(verbose_name='検索結果JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
            ],
            options={
                'verbose_name': '検索キャッシュ',
                'verbose_name_plural': '検索キャッシュ',
                'indexes': [models.Index(fields=['keyword', 'source'], name='myapp_searc_keyword_3b045f_idx')],
            },
        ),
    ]
